sudo: required

language: python

python:
  - "2.7"

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y hostapd dnsmasq

install:
  - pip install pylint
  - python setup.py install

script:
  - pylint --errors-only wifiphisher

branches:
  only:
  - master

notifications:
  email:
    on_success: never
    on_failure: always

  irc:
    channels:
      - "chat.freenode.net#wifiphisher"
    use_notice: true
